name: origa
description: A new Flutter project.

version: 3.0.13+13

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  audio_session: ^0.1.6+1
  connectivity_plus: ^2.2.0
  device_info: ^2.0.3
  dio: ^4.0.4
  dynamic_themes: ^1.1.0
  file_picker: ^4.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_localizations:
    sdk: flutter
  flutter_sound: ^9.1.7
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.23.0+1
  geocoding: ^2.0.1
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  lint: ^1.7.2
#  location_permissions: ^4.0.0
  mime: ^1.0.1
  openid_client: ^0.4.3
  path_provider: ^2.0.5
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.11
  webview_flutter: ^3.0.1
  encrypt: ^5.0.1
  flutter_local_notifications: ^12.0.4
  google_maps_flutter: ^2.2.3
  keyboard_actions: ^4.1.0
  firebase_core: ^2.5.0
  permission_handler: ^10.2.0
  geolocator: ^9.0.2
  fluttertoast: ^8.1.2
  location: ^4.4.0
  package_info_plus: ^1.4.2
  platform_device_id: ^1.0.1
  workmanager: ^0.5.0
  firebase_crashlytics: ^3.0.12
  firebase_database: ^10.0.10
  cloud_firestore: ^4.3.2
  firebase_messaging: ^14.2.2
  ably_flutter: ^1.2.15

dev_dependencies:
  build_runner: ^2.1.4
  equatable: ^2.0.3
  #  flutter_launcher_icons: ^0.9.2
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1

flutter_icons:
  image_path: "assets/app_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/svg/
    - assets/svg/noCaseAvailable.svg
    - assets/app_logo/applogo.png
    - assets/temp_html.html

  fonts:
    - family: Lato-Light
      fonts:
        - asset: fonts/Lato-Light.ttf
    - family: Lato-Medium
      fonts:
        - asset: fonts/Lato-Medium.ttf
    - family: Lato-Regular
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Lato-Semibold
      fonts:
        - asset: fonts/Lato-Semibold.ttf
    - family: Lato-Italic
      fonts:
        - asset: fonts/Lato-Italic.ttf
    - family: Lato-Bold
      fonts:
        - asset: fonts/Lato-Bold.ttf
