name: origa
description: A new Flutter project.

version: 3.0.13+13

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  audio_session: ^0.1.6+1
  connectivity_plus: ^3.0.6
  device_info: ^2.0.3
  dio: ^5.1.1
  dynamic_themes: ^1.1.0
  file_picker: ^5.2.11
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_sound: ^9.1.7
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^2.0.4
  geocoding: ^2.1.0
#  image_picker: ^0.8.7+4
  intl: ^0.18.0
  lint: ^2.0.1
  mime: ^1.0.1
  openid_client: ^0.4.3
  path_provider: ^2.0.5
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.11
  webview_flutter: ^4.2.0
  flutter_local_notifications: ^14.0.0+1
  google_maps_flutter: ^2.3.1
  keyboard_actions: ^4.1.0
  permission_handler: ^10.2.0
  geolocator: ^9.0.2
  fluttertoast: ^8.1.2
  location: ^5.0.0
  package_info_plus: ^4.0.2
  platform_device_id: ^1.0.1
  workmanager: ^0.5.0
  equatable: ^2.0.5
  ably_flutter: ^1.2.15
  go_router: ^8.0.0
  json_annotation: ^4.8.1
  design_system:
    path: core/design_system
  network_helper:
    path: core/network_helper
  domain_models:
    path: core/domain_models
  preference_helper:
    path: core/preference_helper
  repository:
    path: core/repository
  languages:
    path: core/languages
  infinite_scroll_pagination: ^3.2.0
  rxdart: ^0.27.7
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.9.1
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  firebase_database: ^10.2.3

dev_dependencies:
  equatable: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  freezed: ^2.3.5
  json_serializable: ^6.6.2

flutter_icons:
  image_path: "assets/app_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/svg/
    - assets/images/
    - assets/svg/noCaseAvailable.svg
    - assets/svg/collect_logo.svg
    - assets/config/uat.json
    - assets/config/uat_sbic.json
    - assets/config/prod.json
    - assets/config/prod_sbic.json
    - assets/config/dev.json
    - assets/config/poc.json

  fonts:
    - family: Lato-Light
      fonts:
        - asset: fonts/Lato-Light.ttf
    - family: Lato-Medium
      fonts:
        - asset: fonts/Lato-Medium.ttf
    - family: Lato-Regular
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Lato-Semibold
      fonts:
        - asset: fonts/Lato-Semibold.ttf
    - family: Lato-Italic
      fonts:
        - asset: fonts/Lato-Italic.ttf
    - family: Lato-Bold
      fonts:
        - asset: fonts/Lato-Bold.ttf
